name: Build and Test Add-ons

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate Add-ons
        run: |
          docker build ./mariadb -t my-mariadb:latest