name: Validate and Test Add-ons

on:
  pull_request:
    branches:
      - main  # Runs on pull requests targeting the main branch

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate Add-on Configuration
        run: |
          docker build ./mariadb -t mariadb:latest
