name: Build and Publish Add-on

on:
  push:
    branches:
      - main  # Run this workflow on pushes to the main branch

  pull_request:
    branches:
      - main  # Run this workflow for pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          # Specify the directory containing the Dockerfile
          context: ./mariadb
          push: true
          tags: jaleelajmal/mariadb:latest

      - name: Set Docker Hub Description
        run: |
          echo '{"description": "MariaDB add-on for Home Assistant with the latest updates.", "categories": ["Databases", "Home Assistant"]}' > metadata.json
          curl -X PATCH \
            -H "Content-Type: application/json" \
            -u ${{ secrets.DOCKER_USERNAME }}:${{ secrets.DOCKER_PASSWORD }} \
            -d @metadata.json \
            https://hub.docker.com/v2/repositories/jaleelajmal/mariadb/
